### ISSUE TITLE
python3.7 g command fails to shutdown

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#1084]
```
Traceback (most recent call last):
  File "/home/jordi/projects/tracker/env/bin/g", line 8, in <module>
    sys.exit(command_runner())
  File "/home/jordi/projects/tracker/env/lib/python3.9/site-packages/guillotina/commands/__init__.py", line 337, in command_runner
    command.run_command()
  File "/home/jordi/projects/tracker/env/lib/python3.9/site-packages/guillotina/commands/__init__.py", line 175, in run_command
    run_func(app, settings)
  File "/home/jordi/projects/tracker/env/lib/python3.9/site-packages/guillotina/commands/__init__.py", line 190, in __run
    loop.run_until_complete(self.cleanup(app))
  File "/opt/python39/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jordi/projects/tracker/env/lib/python3.9/site-packages/guillotina/commands/__init__.py", line 211, in cleanup
    for task in asyncio.Task.all_tasks():
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
```

**Comment by masipcat** [comment]
I think we want to add compatibility with Py 3.9 on G7, because we'll need to update a lot of libs (probably)

**Comment by jordic** [comment]
I created a new project with it, let's see how it goes.
