### ISSUE TITLE
Happens often on a running site

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina#328]
```Unable to close spurious connection
Traceback (most recent call last):
  File "/Users/ramon/floss/guillotina/guillotina/db/transaction_manager.py", line 76, in begin
    await self._close_txn(txn)
  File "/Users/ramon/floss/guillotina/guillotina/db/transaction_manager.py", line 124, in _close_txn
    await self._storage.close(txn._db_conn)
  File "/Users/ramon/floss/guillotina/guillotina/db/storages/pg.py", line 568, in close
    await shield(self._pool.release(con))
  File "/Users/ramon/floss/guillotina_cms/lib/python3.7/site-packages/asyncpg/pool.py", line 643, in release
    return await asyncio.shield(ch.release(timeout), loop=self._loop)
  File "/Users/ramon/floss/guillotina_cms/lib/python3.7/site-packages/asyncpg/pool.py", line 168, in release
    'PoolConnectionHolder.release() called on '
asyncpg.exceptions._base.InternalClientError: PoolConnectionHolder.release() called on a free connection holder```

**Comment by vangheem** [comment]
Looks like you're running latest asyncpg as we have test issues here from it as well: https://travis-ci.org/plone/guillotina/jobs/421957999

**Comment by vangheem** [comment]
https://github.com/plone/guillotina/pull/298/commits/7ee4315618bcfdec4e1cbb03c342860561582ae8 should fix this error; however, I still need to get tests to pass here.

**Comment by bloodbare** [comment]
It happens after some time its in use, only on write commits. Still need to verify why but in that cases not all data is serialized to db

**Comment by vangheem** [comment]
ouch, it's a different error then because the error I saw was just logged and should not have affected operation.

**Comment by vangheem** [comment]
Still happening? I haven't seen this? Closing.
