### ISSUE TITLE
Patch with long field

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina#370]
On PATCH to a Resource with 
```
{"guillotina_cms.interfaces.base.ICMSBehavior.content_layout":"layout_view"}
```
```Traceback (most recent call last):
  File "/g/lib/python3.7/site-packages/guillotina/traversal.py", line 258, in handler
    view_result = await self.view()
  File "/g/lib/python3.7/site-packages/guillotina/api/content.py", line 270, in __call__
    await notify(ObjectModifiedEvent(self.context, payload=data))
  File "/g/lib/python3.7/site-packages/guillotina/event.py", line 8, in notify
    await subscriber(event)
  File "/g/lib/python3.7/site-packages/guillotina/component/event.py", line 35, in async_dispatch
    return await sitemanager.adapters.asubscribers(event, None)
  File "/g/lib/python3.7/site-packages/guillotina/component/globalregistry.py", line 36, in asubscribers
    results.append(await subscription(*objects))
  File "/g/lib/python3.7/site-packages/guillotina/subscribers.py", line 33, in object_event_notify
    return await sitemanager.adapters.asubscribers((event.object, event), None)
  File "/g/lib/python3.7/site-packages/guillotina/component/globalregistry.py", line 36, in asubscribers
    results.append(await subscription(*objects))
  File "/g/lib/python3.7/site-packages/guillotina/catalog/index.py", line 122, in add_object
    for behavior_field_name in payload[field_name].keys():
AttributeError: 'str' object has no attribute 'keys'```

**Comment by vangheem** [comment]
We should handle this but it's also not a valid patch

**Comment by bloodbare** [comment]
Yups, I know its to handle it better
