### ISSUE TITLE
Unresponsive guillotina after losing connectivity with postgres

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#410]
I'm getting the following error after restarting the postgres:

```
Error on execution of view 343bd8bedf114f8fa853ea44dc5f4388
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/guillotina/traversal.py", line 261, in handler
    await commit(request, warn=False)
  File "/usr/local/lib/python3.7/site-packages/guillotina/transactions.py", line 22, in commit
    await get_tm(request).commit(request)
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction_manager.py", line 99, in commit
    return await shield(self._commit(request=request, txn=txn))
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction_manager.py", line 108, in _commit
    await txn.commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 304, in commit
    return await self._commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 320, in _commit
    await self.tpc_commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 375, in tpc_commit
    await self._strategy.tpc_commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/strategies/resolve.py", line 56, in tpc_commit
    await self.retrieve_tid()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/strategies/base.py", line 29, in retrieve_tid
    tid = await self._storage.get_next_tid(self._transaction)
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/storages/pg.py", line 761, in get_next_tid
    return await self._stmt_next_tid.fetchval()
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connresource.py", line 19, in _check
    self._check_conn_validity(meth.__name__)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/prepared_stmt.py", line 223, in _check_conn_validity
    super()._check_conn_validity(meth_name)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connresource.py", line 44, in _check_conn_validity
    self.__class__.__name__, meth_name))
asyncpg.exceptions._base.InterfaceError: cannot call PreparedStatement.fetchval(): the underlying connection is closed
```

Guillotina is not able to recover itself after loosing connection with postgres. It seems that asyncpg doesn't reconnect automatically on prepared statements.

I think we can fix this using one of the following solutions:

1. Stop using PreparedStatements and rely on the internal asyncpg cache (as suggested here https://github.com/MagicStack/asyncpg/issues/286#issuecomment-385691873)
2. Wrap all the calls to PreparedStatements to catch this exception and recreate the PreparedStatement manually
3. Just make guillotina crash and the supervisor will start a new instance of guillotina with a new pool of connections / PreparedStatements

What do you think? Maybe there are other approaches to solve this bug.

Thank you in advance!

**Comment by vangheem** [comment]
- 1: I agree but I'm not sure it'll fix the issue either
- 2: I guess I'm not convinced it's related to the use of prepared statements with the connection object. Because we already have things like this: https://github.com/plone/guillotina/blob/master/guillotina/db/storages/pg.py#L771
- 3: sometimes I think this is the best approach; however, it seems a little hacky to do a sys.exit too...

I think we do `#1` on the read connection and also try and wrap handle disconnections better.

Make sense?

**Comment by masipcat** [comment]
@vangheem makes sense :) I'll start working on the fix on Monday.

Thank you and have a nice weekend!

**Comment by masipcat** [comment]
After checking a bit it seems that the problem is not related to PrefetchStatements at all and the problem is in `_check_bad_connection()`. The problem is that `restart_connection()` never gets called because this line https://github.com/plone/guillotina/blob/master/guillotina/db/storages/pg.py#L758 doesn't match some of the asyncpg exception:

```python
>>> 'cannot call PreparedStatement.fetchval(): the underlying connection is closed' in ('cannot perform operation: connection is closed', 'connection is closed', 'pool is closed', 'connection was closed')
False
>>> 'connection was closed in the middle of operation' in ('cannot perform operation: connection is closed', 'connection is closed', 'pool is closed', 'connection was closed')
False
```

I suggest replacing the function with this one:

```python
async def _check_bad_connection(self, ex):
     for err in ('connection is closed', 'pool is closed', 'connection was closed'):
          if err in str(ex):
               if (time.time() - self._connection_initialized_on) > BAD_CONNECTION_RESTART_DELAY:
                    # we need to make sure we aren't calling this over and over again
                    return await self.restart_connection()
```

What do you think?

**Comment by vangheem** [comment]
Looks great @masipcat!

Thank you for looking into this.

**Comment by masipcat** [comment]
Thank you @vangheem ! :)
