### ISSUE TITLE
Database connection acquire timeout

### ISSUE THREAD

**Issue by harwee** [plone/guillotina#579]
I tried to use the below piece of code to get container by name

    async def get_container_by_name(request, name):
        async for x in get_containers(request):
            if x[-1].name == name:
                return x

    async def get_user_container(request):
        return await get_container_by_name(request, "user")

This works fine for first few requests. Depending on number of times `get_container_by_name` is called after 6, 12, 18 requests the `transaction.get_connection` timeout and all subsequent requests to server fails irrespective of what they do. Attached is the error log

    Exception on resolve execution
    Traceback (most recent call last):
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/traversal.py", line 368, in resolve
        result = await self.real_resolve(request)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/traversal.py", line 435, in real_resolve
        await self.apply_authorization(request)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/traversal.py", line 530, in apply_authorization
        await participation()
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/auth/participation.py", line 27, in __call__
        user = await authenticate_request(self.request)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/auth/__init__.py", line 20, in authenticate_request
        user = await validator(request).validate(token)
    File "/home/sriharsha/hservice/hservice_core/starshot/guillotina/guillotina_hservice_auth/validators.py", line 151, in validate
        user = await set_permissions(self.request, guillotina_user, user, token_role_perm_info)
    File "/home/sriharsha/hservice/hservice_core/starshot/guillotina/guillotina_hservice_auth/utils.py", line 100, in set_permissions
        _, _, user_container = await get_user_container(request)
    File "/home/sriharsha/hservice/hservice_core/starshot/guillotina/guillotina_hservice_auth/utils.py", line 22, in get_user_container
        return await get_container_by_name(request, HServiceContainer)
    File "/home/sriharsha/hservice/hservice_core/starshot/guillotina/guillotina_hservice_auth/utils.py", line 13, in get_container_by_name
        async for x in get_containers(request):
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/utils/content.py", line 88, in get_containers
        async for c_id, container in db.async_items():
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/factory/content.py", line 240, in async_items
        async for key, value in root._p_jar.items(root):
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/transaction.py", line 489, in items
        keys = await self.keys(container._p_oid)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/transaction.py", line 56, in _wrapper
        result = await func(self, *args, **kwargs)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/transaction.py", line 413, in keys
        for record in await self._manager._storage.keys(self, oid):
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/storages/pg.py", line 914, in keys
        conn = await txn.get_connection()
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/transaction.py", line 138, in get_connection
        self._db_conn = await self._manager._storage.open()
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/storages/pg.py", line 242, in decorator
        return await f(self, *args, **kwargs)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/guillotina/db/storages/pg.py", line 683, in open
        conn = await self.pool.acquire(timeout=self._conn_acquire_timeout)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/site-packages/asyncpg/pool.py", line 607, in _acquire
        _acquire_impl(), timeout=timeout, loop=self._loop)
    File "/home/sriharsha/anaconda3/envs/guillotina/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
        raise futures.TimeoutError()
    concurrent.futures._base.TimeoutError

when `get_object_by_oid` is used everything works fine. Is there any particular reason the above code fails?

**Comment by vangheem** [comment]
`get_containers` iterates through each container in each database yielding `txn, tm, container` for each container object.

The `txn` is an active transaction to the database.

It seems the usage of `get_container` can be unsafe then if you don't finish the iterations(which closes the connection after done).

For example, check out the following example code to demonstrate the problem with this async iterator design::

```
def iterate_values():
    for idx in range(5):
        print(f'found {idx}')
        yield idx
        print(f'cleanup {idx}')

def dosomething():
    for idx in iterate_values():
        if idx == 3:
            return

dosomething()
```

This prints:
```
found 0
cleanup 0
found 1
cleanup 1
found 2
cleanup 2
found 3
```

Now, if we see how this applies to guillotina's `get_containers`, you can see why the db conn might not ever get closed: https://github.com/plone/guillotina/blob/master/guillotina/utils/content.py#L107

Can you make sure after you are doing with the container, you do a `await tm.abort(txn=txn)`?

Another option to manually get your container and manage the txn yourself.

@bloodbare I think you have done a lot of work with working with multiple databases in a single request--do you have any other tips here?

**Comment by harwee** [comment]
That solves the issue but I cannot understand one thing, since most of the time get_containers is called during a request and each request already has a transaction associated with it at `_txn` why should a new transaction be associated with container? why not just set request transaction as container transaction, since that gets aborted when request is complete?

**Comment by harwee** [comment]
I ended up doing this

    async def get_container_by_id(request, cid):
        root = getUtility(IApplication, name='root')
        for _id, db in root:
            if IDatabase.providedBy(db):
                return await db.async_get(cid)

**Comment by vangheem** [comment]
well, the API was originally designed around the concept of having the request object be the state manager. In Guillotina 5, we decoupled everything from the request object and we're using contextvars now(python > 3.7 only).

So, interacting with multiple databases in one request, is not something we typically do or have designed the API to do. In Guillotina 5, it's much less obtuse though.

In any case, you might want to consider a micro-services approach to solving this problem.

I'll close but please reopen if you have anything further!
