### ISSUE TITLE
Using CookieAuthPolicy breaks G6

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina#753]
request object does not have cookie attribute and does not propagate cookies from asgi server

```
Traceback (most recent call last):
  File "/Users/ramon/floss/guillotina/guillotina/traversal.py", line 394, in resolve
    result = await self.real_resolve(request)
  File "/Users/ramon/floss/guillotina/guillotina/traversal.py", line 448, in real_resolve
    authenticated = await authenticate_request(request)
  File "/Users/ramon/floss/guillotina/guillotina/auth/utils.py", line 21, in authenticate_request
    token = await policy(request).extract_token()
  File "/Users/ramon/floss/guillotina/guillotina/auth/extractors.py", line 88, in extract_token
    token = self.request.cookies.get("auth_token")
AttributeError: 'Request' object has no attribute 'cookies'
```

**Comment by masipcat** [comment]
Can you share a snippet or test to reproduce it? I never used this authenticator

**Comment by bloodbare** [comment]
You just need to enable it on auth extractors and do any API operation:

```
auth_extractors:
- guillotina.auth.extractors.CookiePolicy
- guillotina.auth.extractors.BearerAuthPolicy
- guillotina.auth.extractors.BasicAuthPolicy
- guillotina.auth.extractors.WSTokenAuthPolicy
````

**Comment by bloodbare** [comment]
You can also check aiohttp cookie get and set for request object support:
https://github.com/aio-libs/aiohttp/search?p=4&q=cookie&unscoped_q=cookie
