### ISSUE TITLE
Error on es-migrate

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#844]
Seems related to soemthing on transaction

Stack:

```
Traceback (most recent call last):
  File "/home/jordi/Documents/vinissimus/api/env/bin/g", line 11, in <module>
    load_entry_point('guillotina', 'console_scripts', 'g')()
  File "/home/jordi/Documents/newsletter_store/src/guillotina/guillotina/commands/__init__.py", line 337, in command_runner
    command.run_command()
  File "/home/jordi/Documents/newsletter_store/src/guillotina/guillotina/commands/__init__.py", line 175, in run_command
    run_func(app, settings)
  File "/home/jordi/Documents/newsletter_store/src/guillotina/guillotina/commands/__init__.py", line 189, in __run
    self.run(self.arguments, settings, app.app)
  File "/home/jordi/Documents/vinissimus/api/env/lib/python3.7/site-packages/guillotina_elasticsearch/commands/migrate.py", line 76, in run
    loop.run_until_complete(self.migrator.cancel_migration())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/jordi/Documents/vinissimus/api/env/lib/python3.7/site-packages/guillotina_elasticsearch/migration.py", line 535, in cancel_migration
    async with transaction(adopt_parent_txn=True):
  File "/home/jordi/Documents/newsletter_store/src/guillotina/guillotina/transactions.py", line 114, in __aenter__
    self.txn = await self.tm.begin(read_only=self.read_only)
AttributeError: 'NoneType' object has no attribute 'begin'
```

**Comment by vangheem** [comment]
This with g6?

**Comment by jordic** [comment]
Also with g5.
